channels:
- conda-forge
dependencies:
- python=3.8.8
- pip
- pip:
  - mlflow
  - cffi==1.14.5
  - cloudpickle==1.6.0
  - defusedxml==0.7.1
  - dill==0.3.5.1
  - google-auth==2.6.6
  - ipython==7.33.0
  - onnx==1.11.0
  - pathlib==1.0.1
  - torch==1.11.0
  - torchvision==0.12.0
  - tqdm==4.59.0
name: mlflow-env
